/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema;

import banco.Banco;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Autores;
import objetos.Livros;
import objetos.converterData;
/**
 *
 * @author Vinicius
 */
public class AutoresView extends javax.swing.JFrame {
    
    Banco banco = new Banco();
    Autores autores = new Autores();
    Livros livros = new Livros();
    converterData date = new converterData();
    
    /**
     * Creates new form AutoresView
     */
    public AutoresView() {
        initComponents();
        atualizarAutor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textDataDeNascimento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAutores = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(567, 261));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, -1, -1));

        jLabel2.setText("Data Nascimento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 140, -1));
        getContentPane().add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 218, 306, -1));
        getContentPane().add(textDataDeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 100, -1));

        tableAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAutoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAutores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 570, 190));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, -1));

        btnSalvar.setText("Inserir");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 80, -1));

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 80, -1));

        btnEditar.setText("Alterar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 80, -1));

        setBounds(0, 0, 625, 341);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        atualizarAutor();
        DefaultTableModel model = (DefaultTableModel) tableAutores.getModel();
        model.addRow(new Object[] {null, null});
        limparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {
            String data, dataISO;
            
            data = textDataDeNascimento.getText();
            dataISO = date.parseDataIso(data);
            
            autores.setNome(textNome.getText());
            autores.setData_nascimento(dataISO);
            banco.inserirAutores(autores);
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(AutoresView.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizarAutor();
        limparCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int y = 0;
        
        if(y == JOptionPane.showConfirmDialog(null, "Tem certeja que deseja excluir?", "Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE))
        {
                banco.excluirAutores(autores.getId());
                atualizarAutor();
                limparCampos();
        } 
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(autores.getId() != 0)
        {
            int x = tableAutores.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tableAutores.getModel();
            String nome = textNome.getText();
            String data = textDataDeNascimento.getText();
            String dataISO;
            dataISO = date.parseDataIso(data);
            
            autores.setNome(nome);
            autores.setData_nascimento(dataISO);
            
            banco.alterarAutores(autores);
            limparCampos();
            atualizarAutor();
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tableAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAutoresMouseClicked

        int x = tableAutores.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableAutores.getModel();
        
        int id;
        String nome = model.getValueAt(x, 0).toString();
        String data = model.getValueAt(x, 1).toString();
        String dataISO;
        dataISO = date.parseDataIso(data);
        
        autores.setNome(nome);
        autores.setData_nascimento(dataISO);
        
        id = banco.acharID(autores);
        autores.setId(id);
        
        textNome.setText(nome);
        textDataDeNascimento.setText(data);
        
    }//GEN-LAST:event_tableAutoresMouseClicked

    public void atualizarAutor()
    
    {
        Connection con;
        try
        {
            con = banco.Conectar();
            Statement stmt =con.createStatement();					
            String sqlStmt =  "SELECT "
                             +"       nome, "
                             +"       data_nascimento"
                             +"   FROM "
                             +"       autores "
                             +"   ORDER BY "
                             +"           nome ASC";
            ResultSet rSet = stmt.executeQuery(sqlStmt); 

            DefaultTableModel model = (DefaultTableModel) tableAutores.getModel(); 

            int x = model.getRowCount();  
            for(int a = 0; a < x; a++)  
            {  
                model.removeRow(0);  
            }  


            while (rSet.next()) 
            {
                String nome, data, dataBR;
                nome = rSet.getString("nome");
                data = rSet.getString("data_nascimento");
                dataBR = date.parseDataBra(data);

                model.addRow(new String[] {nome, dataBR} );
            }

        }
        
        catch(Exception e){

            JOptionPane.showMessageDialog(null,"Erro -> "+e.getMessage().toString()); 	

        }
    }
    
    public void limparCampos()
    {
        textNome.setText(null);
        textDataDeNascimento.setText(null);
        textNome.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoresView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAutores;
    private javax.swing.JTextField textDataDeNascimento;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
